strictness: veryhigh

pep8:
  disable:
    - N802
    - W503
  options:
    max-line-length: 120

pyflakes:
  disable:
    - F405

pylint:
  disable:
    - no-value-for-parameter
    - logging-fstring-interpolation
  options:
      max-line-length: 120
